default_install_hook_types:
- pre-commit
- post-checkout
- pre-commit
repos:
# Prohibits commits to the default branch
# TODO: Revive this after publishing of the first version
# - repo: https://github.com/pre-commit/pre-commit-hooks
#   rev: v4.2.0
#   hooks:
#   - id: no-commit-to-branch
#     args: [--branch, main]
- repo: local
  hooks:
  - id: pre-commit-run-hpack
    name: Generates .cabal files with hpack
    always_run: true
    verbose: true
    stages: [commit]
    language: system
    pass_filenames: false
    entry: bash -c "find . \( -name '**/*.cabal' -or -name '**/cabal.project*' \) -not -path './dist-newstyle/*' | while read -r FILE; do cabal-gild --io "\${FILE}"; done || echo '[warn] no cabal-gild found' >&2"
